### ISSUE TITLE
Leaking global `addresses` in downstream dep `uniqid`

### ISSUE THREAD

**Issue by jwalton** [postcss/postcss-filter-plugins#16]
The package [macaddress](https://github.com/scravy/node-macaddress) has a global leak in v0.2.8.  This appears to be fixed in their master, but they haven't pushed the fix for [9 months](https://github.com/scravy/node-macaddress/issues/7).

The package [uniqid](https://github.com/adamhalasz/uniqid) relies on macaddress, so I'd like to harass them into switching from macaddress to some other package, but they were [made aware of this issue six months ago](https://github.com/adamhalasz/uniqid/issues/8), and they still haven't done anything.

So, I come to you.  :)  postcss-filter-plugins is a dependency of cssnano, which is a dependency of css-loader, which means quite a few webpack based projects get postcss-filter-plugins as an indirect dependency, and all of those projects will have mysterious test failures if they pass `--check-leaks` to mocha, so it would be nice to get this fixed.  :)  Can we replace `uniqid` with another library easily?

**Comment by jwalton** [comment]
https://github.com/postcss/postcss-filter-plugins/pull/15 would fix it perfectly, BTW.

**Comment by RyanZim** [comment]
Fixed in https://github.com/postcss/postcss-filter-plugins/pull/19.
